seed: 42
deterministic: true

task:
  type: classification        # classification | binary | regression
  num_classes: 10             # required for classification
  threshold: 0.5              # used for binary only
  metrics: [accuracy, f1_macro, precision_macro, recall_macro]  # choose what to print/log
  # For regression you might use:
  # metrics: [mse, mae, rmse, r2, mape]  # add 'mase' if you have time-series
  # mase_m: 12                           # seasonality for MASE (required if you include 'mase')


data:
  name: CIFAR10
  root: ./data
  num_workers: 4
  batch_size: 128
  aug: basic         # none | basic | auto
  cutout: 0          # pixels of square cutout, e.g. 8 (0 disables)
  shuffle_train: true          # set false for time-series (MASE needs ordered data)

model:
  name: resnet18     # resnet18 | smallcnn
  dropout: 0.0       # only used by smallcnn
  # output size is derived from task.* (no need to set here)

optim:
  name: adamw        # adam | sgd | adamw
  lr: 3.0e-3
  weight_decay: 0.02
  momentum: 0.9      # if using sgd

scheduler:
  name: cosine       # cosine | onecycle | step | reduce_on_plateau | none
  epochs: 100
  warmup_epochs: 5
  step_size: 30      # for step
  gamma: 0.1         # for step
  pct_start: 0.3     # for onecycle
  reduce_patience: 10
  reduce_factor: 0.5

train:
  epochs: 100
  grad_clip_norm: 1.0
  amp: true
  log_interval: 100
  early_stopping_patience: 20
  label_smoothing: 0.0     # try 0.1 for extra robustness
  save_dir: ./runs/cifar10_resnet18

logging:
  use_tensorboard: true
  use_wandb: false
  wandb_project: test_project